window.seedDataset = {
  title: "投行观点雷达",
  source: {
    name: "金十海外研报",
    dashboardUrl:
      "https://admins.jin10.com/report_admin/#/report-foreign/research?page=1&pageSize=50",
    apiBase: "https://cada611924f84b7eb1b95b425dbb1e7d.z3c.jin10.com/overseas_data",
    snapshotDate: "2026-04-03",
    pages: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    institutions: ["高盛", "摩根士丹利", "花旗", "美银", "摩根大通", "瑞银"],
  },
  events: [
    {
      id: "jin10-ubs-commodities-20260403",
      date: "2026-04-03",
      title: "瑞银：能源仍是商品主驱动，黄金继续做地缘对冲",
      type: "大宗商品月报",
      institution: "瑞银",
      desk: "全球大宗商品策略",
      theme: "能源冲击",
      quote: "即便地缘紧张缓和，供给约束也不会立刻消失，商品里真正有持续性的还是能源和黄金。",
      summary:
        "瑞银 4 月商品观点认为，原油和液化天然气供应仍受霍尔木兹海峡扰动约束，卡塔尔相关基础设施修复可能以年而不是月计，全球库存因此持续回落。与此同时，工业金属需求恢复会被更高能源成本继续推迟，而黄金仍会受益于央行需求、增长担忧和地缘对冲需求。",
      takeaway:
        "商品配置可以继续保留，但真正的主线还是能源和黄金。",
      conviction: 84,
      surprise: 76,
      divergence: 73,
      sourceId: 613520,
      signals: [
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 84,
          horizon: "1-3月",
          driver: "海湾运输受阻与液化天然气供应紧张仍在压低库存，油价高位更容易延续而不是快速回落",
          expression: "原油继续按供给受限与库存下滑处理，不把缓和消息当成趋势反转",
          invalidation: "霍尔木兹海峡运输和炼化物流恢复快于预期，库存重新明显回补",
        },
        {
          asset: "黄金",
          direction: "bullish",
          score: 82,
          horizon: "6-12月",
          driver: "央行需求、增长担忧与地缘对冲需求仍在，黄金继续承担组合保险功能",
          expression: "黄金维持核心配置，不因短线波动轻易削减",
          invalidation: "实际利率持续大幅上行并显著压制配置需求",
        },
        {
          asset: "铜",
          direction: "bearish",
          score: 69,
          horizon: "1-3月",
          driver: "能源冲击会推迟中国、美国和欧洲的工业金属需求修复",
          expression: "铜先按需求恢复延后处理，等待成本与需求重新匹配",
          invalidation: "全球制造业和电网投资需求明显超预期回升",
        },
      ],
    },
    {
      id: "jin10-ubs-global-conflict-20260403",
      date: "2026-04-03",
      title: "瑞银：市场还没真正按长期冲突定价，油到150美元附近才会逼出衰退风险",
      type: "全球宏观情景",
      institution: "瑞银",
      desk: "全球经济与策略",
      theme: "宏观策略",
      quote: "市场还在赌快速解决，但一旦扰动拉长，增长损失和政策分化都会突然变大。",
      summary:
        "瑞银把中东冲突分成快速解决、霍尔木兹海峡两个月受阻、以及更长期基础设施受损三种情景。其判断是，市场目前仍在按较快缓和定价，但如果油价接近 150 美元并演变成更长期冲击，全球增长损失会显著放大，亚洲和欧洲风险资产会先承压，而美元会先走强、随后在更鸽的美联储路径下转弱。",
      takeaway:
        "当前最容易被低估的不是短线波动，而是冲突拖长后增长和政策路径的突变。",
      conviction: 88,
      surprise: 80,
      divergence: 82,
      sourceId: 613477,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 78,
          horizon: "短期",
          driver: "在最剧烈的波动阶段，美元仍是主要避险货币，尤其会先压制亚洲风险资产与新兴市场货币",
          expression: "美元先按急性冲击中的避险腿处理",
          invalidation: "冲突迅速降温且油价明显回落，避险需求同步退潮",
        },
        {
          asset: "亚洲股票",
          direction: "bearish",
          score: 84,
          horizon: "1-3月",
          driver: "亚洲对进口能源更敏感，一旦扰动拖长，盈利与风险偏好都会更快受压",
          expression: "亚洲顺周期和能源敏感板块继续偏保守",
          invalidation: "海湾运输恢复和能源价格显著回落快于预期",
        },
        {
          asset: "美国10年期国债",
          direction: "bullish",
          score: 77,
          horizon: "3-12月",
          driver: "如果冲突拖长并伤及增长，美债长端收益率中期更可能见顶后回落",
          expression: "美债久期更适合中期而不是当下追逐",
          invalidation: "通胀冲击持续扩散并压制所有降息预期",
        },
        {
          asset: "黄金",
          direction: "bullish",
          score: 75,
          horizon: "3-12月",
          driver: "一旦增长担忧压过通胀担忧，黄金会重新恢复更强的分散与对冲作用",
          expression: "黄金仍保留中期上行空间，不把当前表现当成失效",
          invalidation: "实际利率长期维持高位且增长风险没有兑现",
        },
      ],
    },
    {
      id: "jin10-ubs-gold-20260403",
      date: "2026-04-03",
      title: "瑞银：下调短期黄金目标，但年末目标仍看5900美元",
      type: "黄金专题",
      institution: "瑞银",
      desk: "全球贵金属策略",
      theme: "宏观策略",
      quote: "短线逆风变多，但这更像节奏调整，不是黄金长期逻辑被破坏。",
      summary:
        "瑞银把黄金 6 月目标从 6200 下调到 5200 美元，原因是强美元、高油价和降息预期回摆短线抬升了实际利率。但它同时维持 2026 年末 5900 美元的目标，认为央行需求、滞胀风险、美国大选不确定性以及中长期更弱的美元路径，仍会把黄金重新推回上行通道。",
      takeaway:
        "黄金短线要接受更大波动，但中期配置逻辑没有变。",
      conviction: 83,
      surprise: 78,
      divergence: 75,
      sourceId: 613512,
      signals: [
        {
          asset: "黄金",
          direction: "bullish",
          score: 83,
          horizon: "6-12月",
          driver: "央行买盘、滞胀风险和更弱美元的中期路径仍支撑黄金重新上行",
          expression: "黄金按中期配置处理，接受短线波动但不改年内偏多",
          invalidation: "实际利率与美元同步持续大幅走强",
        },
        {
          asset: "美国10年期国债",
          direction: "bullish",
          score: 68,
          horizon: "3-12月",
          driver: "若增长担忧接管市场，实际利率后续回落会重新抬升贵金属和久期资产吸引力",
          expression: "久期与黄金可作为同一中期防御链条配置",
          invalidation: "通胀持续失控并迫使长端收益率继续上冲",
        },
        {
          asset: "美元",
          direction: "bearish",
          score: 65,
          horizon: "6-12月",
          driver: "瑞银仍认为长期美元路径偏弱，这是黄金中期上行的重要支撑之一",
          expression: "不把短线美元强势延伸成全年单边趋势",
          invalidation: "全球风险长期恶化并让美元避险需求持续强化",
        },
      ],
    },
    {
      id: "jin10-gs-macro-roadmap-20260403",
      date: "2026-04-03",
      title: "高盛：冲突拖得越久，商品价格下限越高，市场必须按更持久冲击重估",
      type: "宏观路线图",
      institution: "高盛",
      desk: "全球宏观策略",
      theme: "能源冲击",
      quote: "现在已经不只是事件冲击，市场要开始重新计算更长时间的能源约束会留下什么后果。",
      summary:
        "高盛认为，随着冲突延续，市场已经不能再把它只当作一次短期事件。其基线情景仍是假设霍尔木兹海峡 6 周处在极低流量后逐步恢复，但若时间继续拉长，商品价格中枢、运输约束、精炼产品短缺和亚洲输入型压力都会变得更持久，即使最终缓和，去库存和基础设施损伤也会抬高多个商品的底部价格。",
      takeaway:
        "越往后看，真正重要的不是 headline，而是供给约束会不会从价格问题变成数量问题。",
      conviction: 86,
      surprise: 81,
      divergence: 79,
      sourceId: 613494,
      signals: [
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 86,
          horizon: "1-3月",
          driver: "冲突持续时间越长，商品价格路径越偏向更高的平台而不是一次性脉冲",
          expression: "布伦特继续按高底部高波动处理",
          invalidation: "霍尔木兹海峡流量恢复与能源设施修复明显快于基线",
        },
        {
          asset: "柴油",
          direction: "bullish",
          score: 80,
          horizon: "短中期",
          driver: "精炼产品尤其航煤和柴油已经出现更高油当量价格，说明约束正向下游扩散",
          expression: "精炼品优先级抬升，不只盯原油本身",
          invalidation: "炼化和运输链条同步恢复并缓解下游紧张度",
        },
        {
          asset: "原油波动率",
          direction: "bullish",
          score: 84,
          horizon: "短中期",
          driver: "供给、运力和政策表态同时在变，油价分布会持续拉宽",
          expression: "继续用波动率思路看油而不是单押方向",
          invalidation: "地缘风险快速收敛且库存恢复明显",
        },
        {
          asset: "亚洲股票",
          direction: "bearish",
          score: 74,
          horizon: "1-3月",
          driver: "输入型能源压力更容易先压低亚洲的增长与风险偏好",
          expression: "亚洲能源敏感资产继续偏保守配置",
          invalidation: "亚洲能源供给约束解除且外需同步改善",
        },
      ],
    },
    {
      id: "jin10-gs-fed-hikes-20260402",
      date: "2026-04-02",
      title: "高盛：市场高估了油价会逼出美联储重新加息的概率",
      type: "美国宏观评述",
      institution: "高盛",
      desk: "美国经济研究",
      theme: "利率交易",
      quote: "油价上去不等于美联储就要重新抬手，当前经济起点和金融条件都不支持这一点。",
      summary:
        "高盛指出，自伊朗冲突以来，市场对 2026 年美联储重新加息的定价显著上升，但它认为这种担忧被夸大了。原因在于本轮供给冲击比历史上的高通胀阶段更窄、更小，劳动力市场正在走软，通胀预期仍相对受锚定，而且金融条件自冲突以来已经显著收紧，美联储通常也不会仅因油价冲击本身而加息。",
      takeaway:
        "市场现在更像是在过度交易再通胀尾部，而不是在交易真正高概率的加息路径。",
      conviction: 84,
      surprise: 74,
      divergence: 77,
      sourceId: 613270,
      signals: [
        {
          asset: "美债2年",
          direction: "bullish",
          score: 78,
          horizon: "1-3月",
          driver: "若市场重新下修对美联储加息的误判，前端利率先有修复空间",
          expression: "前端美债更适合交易加息溢价回吐",
          invalidation: "能源冲击显著扩散到核心通胀并迫使美联储改口",
        },
        {
          asset: "美国10年期国债",
          direction: "bullish",
          score: 74,
          horizon: "1-3月",
          driver: "供给冲击并不天然意味着更高终端利率，长债当前更受过度鹰派定价影响",
          expression: "长债先按市场高估加息风险后的修复窗口看待",
          invalidation: "增长仍稳而通胀持续再抬头，长端收益率重新上冲",
        },
      ],
    },
    {
      id: "jin10-jpm-g10-fx-20260402",
      date: "2026-04-02",
      title: "摩根大通：继续卖美元兑日元反弹，英镑反弹仍适合逢高回落",
      type: "G10外汇",
      institution: "摩根大通",
      desk: "全球外汇交易",
      theme: "外汇交易",
      quote: "现在不是对 relief rally 上头的时候，还是先做相对价值和反弹回落。",
      summary:
        "摩根大通认为，月底与 headline 交织令外汇市场非常混乱，但策略上仍更偏向相对价值而不是追逐单边行情。其组合继续倾向逢高卖出美元兑日元，英镑反弹后仍更适合继续逢高回落；欧元虽出现更明显的空头回补，但还不足以说明市场已经真正走出风险区。",
      takeaway:
        "G10 外汇仍是防守优先，先做反弹卖出和相对价值，不急着追 relief rally。",
      conviction: 81,
      surprise: 72,
      divergence: 74,
      sourceId: 613276,
      signals: [
        {
          asset: "日元",
          direction: "bullish",
          score: 83,
          horizon: "短期",
          driver: "在不确定性仍高的阶段，日元仍是更直接的防御型相对价值表达",
          expression: "继续逢高卖出美元兑日元，把日元当避险腿处理",
          invalidation: "风险偏好显著修复并压低避险需求",
        },
        {
          asset: "英镑",
          direction: "bearish",
          score: 78,
          horizon: "短期",
          driver: "英镑更容易在 headlines 反弹中被重新卖出，基本面还不足以支持持续上行",
          expression: "英镑继续逢高回落，不追反弹",
          invalidation: "英国资产和风险偏好同步出现超预期改善",
        },
        {
          asset: "欧元",
          direction: "neutral",
          score: 65,
          horizon: "短期",
          driver: "欧元出现空头回补，但还不到可以积极追高的阶段",
          expression: "欧元暂时按震荡和区间处理",
          invalidation: "地缘风险明显退潮并确认欧洲增长预期修复",
        },
      ],
    },
    {
      id: "jin10-ms-global-gas-lng-20260402",
      date: "2026-04-02",
      title: "摩根士丹利：液化天然气船上库存已经交付完，4月现货会更紧",
      type: "全球燃气追踪",
      institution: "摩根士丹利",
      desk: "全球天然气策略",
      theme: "能源冲击",
      quote: "就算缓和也只是把尾部风险拿掉，现货平衡仍然会因为补库存而继续偏紧。",
      summary:
        "摩根士丹利指出，全球约 20% 的液化天然气供应仍处于离线状态，而中东冲突前已经在海上的那批货几乎都已完成交付，这意味着 4 月开始现货市场会更紧。其基线情景仍是假设卡塔尔与阿联酋出口体系在 3-4 月受扰、拉斯拉凡部分产线多年停摆，并预计 2026 年仍会留下大约 1500 万吨的供给缺口。",
      takeaway:
        "液化天然气现在不只是 headline 交易，而是正在进入更硬的现货紧平衡阶段。",
      conviction: 89,
      surprise: 82,
      divergence: 83,
      sourceId: 613386,
      signals: [
        {
          asset: "LNG",
          direction: "bullish",
          score: 90,
          horizon: "1-3月",
          driver: "海上库存交付完成后，现货市场要直接面对供给缺口和补库存需求",
          expression: "液化天然气继续按更紧现货市场和补库存逻辑处理",
          invalidation: "海湾供给恢复与新增出口进度明显快于预期",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 85,
          horizon: "1-3月",
          driver: "欧洲仍会承接全球液化天然气再定价与库存焦虑",
          expression: "欧洲天然气继续按高波动高价格处理",
          invalidation: "欧洲锁定替代气源并显著缓解库存压力",
        },
        {
          asset: "美国天然气",
          direction: "bullish",
          score: 72,
          horizon: "短中期",
          driver: "美国新增出口启动和供应扰动并存，使美国天然气更受全球外溢需求支撑",
          expression: "美国天然气按出口链受益方向看待",
          invalidation: "全球液化天然气价格回落并削弱出口吸引力",
        },
      ],
    },
    {
      id: "jin10-bofa-energy-structure-20260402",
      date: "2026-04-02",
      title: "美银：更值得押的是北美液化天然气与能源运输链，不只是单纯油价弹性",
      type: "能源结构专题",
      institution: "美银",
      desk: "美国能源策略",
      theme: "能源冲击",
      quote: "如果冲突没有真正干净结束，能源安全会把需求和资本支出都重新导向北美出口链。",
      summary:
        "美银认为，本轮冲突真正值得盯的不是单纯油价 beta，而是冲突后可能留下的结构变化。其判断包括三点：全球会更积极回补战略油储、北美特别是液化天然气和液体运输出口链会继续抢占份额、加拿大和北美管道运输能力会受益。相比单纯赌油价股，它更偏好长期基础设施赢家。",
      takeaway:
        "真正有持续性的，不是油价弹一下，而是能源安全重构后谁能稳定把货运出去。",
      conviction: 84,
      surprise: 77,
      divergence: 80,
      sourceId: 613406,
      signals: [
        {
          asset: "LNG",
          direction: "bullish",
          score: 85,
          horizon: "6-12月",
          driver: "北美液化天然气在新的能源安全框架下会持续提升全球份额",
          expression: "能源链里继续优先看液化天然气出口能力",
          invalidation: "全球冲突快速彻底解决并削弱对冗余供应链的需求",
        },
        {
          asset: "美国天然气",
          direction: "bullish",
          score: 77,
          horizon: "6-12月",
          driver: "出口链扩张和供给安全偏好上升，会抬升美国天然气中期战略价值",
          expression: "美国天然气更多按出口与基础设施受益逻辑处理",
          invalidation: "新增出口受阻或全球天然气价差快速收敛",
        },
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 72,
          horizon: "3-12月",
          driver: "战略油储回补和更高安全库存需求会抬高油价中期底部",
          expression: "布伦特中期底部抬高，不轻易回到战前低位",
          invalidation: "全球需求明显走弱并压过补库存需求",
        },
      ],
    },
    {
      id: "jin10-gs-gold-20260402",
      date: "2026-04-02",
      title: "高盛：黄金短线会被强美元和高油价压着走，但年底仍看5400",
      type: "贵金属专题",
      institution: "高盛",
      desk: "全球贵金属策略",
      theme: "宏观策略",
      quote: "金价这次回撤更像仓位和利率路径的再定价，不是避险功能失效。",
      summary:
        "高盛指出，黄金自中东冲突爆发后回撤约 15%，主要原因是前期看涨期权仓位过重、权益回撤触发流动性抛售，以及市场把美联储路径重新定价为更少降息。尽管如此，高盛仍维持 2026 年底 5400 美元目标，认为央行分散配置和后续降息仍会把黄金重新推回上行通道。",
      takeaway:
        "黄金短线要接受更剧烈的去杠杆，但中期逻辑仍然完整。",
      conviction: 82,
      surprise: 77,
      divergence: 76,
      sourceId: 613257,
      signals: [
        {
          asset: "黄金",
          direction: "bullish",
          score: 80,
          horizon: "6-12月",
          driver: "央行分散配置、投机仓位回归正常和后续降息预期仍支持黄金在年内修复",
          expression: "黄金按中期回升处理，不把当前回撤当成趋势反转",
          invalidation: "霍尔木兹海峡扰动持续叠加强美元和高实际利率，继续压缩配置需求",
        },
        {
          asset: "美元",
          direction: "bullish",
          score: 66,
          horizon: "短期",
          driver: "短线更少降息和能源冲击会让美元继续压制黄金表现",
          expression: "美元短线仍是黄金的逆风，不急着押单边金价反转",
          invalidation: "市场重新恢复对降息的明确定价并压低美元",
        },
      ],
    },
    {
      id: "jin10-gs-oil-tracker-20260326",
      date: "2026-03-26",
      title: "高盛：Hormuz 只是局部放松，油流离正常还很远",
      type: "Oil Tracker",
      institution: "高盛",
      desk: "全球大宗商品",
      theme: "能源冲击",
      quote: "市场会对谈判 headline 起反应，但真正决定价格的是油流恢复有没有回到正常。",
      summary:
        "高盛指出，尽管美国与伊朗方案讨论让市场短线波动，但 Hormuz 4 日均值油流仍较正常低 96%，波斯湾总油流受损约 1500 万桶/日。伊朗对过境施加条件和费用，Bab al-Mandeb 也仍具扰动风险，亚洲开始通过高价采购俄罗斯原油和压缩需求来被动适应。",
      takeaway:
        "先把主线放在低油流与运输约束，而不是把谈判 headline 当成供给恢复。",
      conviction: 89,
      surprise: 82,
      divergence: 84,
      sourceId: 612232,
      signals: [
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 90,
          horizon: "1-3月",
          driver: "Hormuz 油流仍远低于正常水平，运输与过境费用抬升让现货油价继续保有高风险溢价",
          expression: "布伦特继续按高位高波动处理，不把 headline 回落当成趋势反转",
          invalidation: "Hormuz 实际恢复正常通航且波斯湾出口快速回补",
        },
        {
          asset: "原油波动率",
          direction: "bullish",
          score: 86,
          horizon: "短中期",
          driver: "谈判、收费、封锁与二次扰动交织，让油价更容易在 headline 间剧烈摆动",
          expression: "原油更适合用波动率而不是单边方向去表达",
          invalidation: "地缘谈判取得实质进展并显著压低运输扰动",
        },
        {
          asset: "LNG",
          direction: "bullish",
          score: 81,
          horizon: "1-3月",
          driver: "亚洲通过替代原油和压缩需求来应对海湾受阻，会继续把 LNG 链条推向更紧的平衡",
          expression: "继续把 LNG 当成海湾能源冲击的核心观察点",
          invalidation: "海湾流量修复快于预期且替代供给明显增加",
        },
      ],
    },
    {
      id: "jin10-gs-fx-growth-usd-20260326",
      date: "2026-03-26",
      title: "高盛：若市场开始交易增长下行，美元、日元、瑞郎会继续跑赢",
      type: "FX Trader Call",
      institution: "高盛",
      desk: "全球外汇策略",
      theme: "外汇交易",
      quote: "当冲击从通胀定价转向增长定价，真正跑赢的会是避险货币而不是高 beta 反弹。",
      summary:
        "高盛认为市场当前仍更多在交易能源冲击的通胀后果，但若冲突持续并开始拖累增长，金融条件收紧会从利率主导逐渐转向增长主导，届时美元、日元、瑞郎会更稳定跑赢，而高 beta G10 与新兴市场货币会继续承压。",
      takeaway:
        "不要过早把短线反弹理解成风险偏好修复，外汇主线仍偏避险货币。",
      conviction: 84,
      surprise: 77,
      divergence: 78,
      sourceId: 612177,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 82,
          horizon: "短期",
          driver: "金融条件收紧仍先通过利率与流动性渠道体现，美元在防御阶段继续受益",
          expression: "美元继续作为第一层宏观对冲",
          invalidation: "停火和能源缓和迅速落地并让增长担忧退潮",
        },
        {
          asset: "日元",
          direction: "bullish",
          score: 84,
          horizon: "短中期",
          driver: "一旦市场从通胀切向增长担忧，日元比高 beta 货币更容易获得保护性买盘",
          expression: "日元继续作为增长下行场景下的核心避险腿",
          invalidation: "风险偏好全面修复并重新转向顺周期资产",
        },
        {
          asset: "瑞郎",
          direction: "bullish",
          score: 79,
          horizon: "短中期",
          driver: "在增长和地缘双重不确定下，瑞郎仍具更稳定的防御属性",
          expression: "瑞郎保留避险配置，不急于回补风险货币",
          invalidation: "欧洲风险明显回落且避险需求快速降温",
        },
        {
          asset: "英镑",
          direction: "bearish",
          score: 74,
          horizon: "短期",
          driver: "高能源成本与增长担忧同时存在时，英镑更容易被当成反弹卖出的高 beta 货币",
          expression: "英镑反弹以减仓和做空为主，不追涨",
          invalidation: "英国数据和风险偏好同步改善",
        },
        {
          asset: "高beta货币",
          direction: "bearish",
          score: 80,
          horizon: "短中期",
          driver: "增长风险升温时，市场会先回避周期敏感和外部脆弱的货币篮子",
          expression: "高 beta 货币继续按反弹卖出框架处理",
          invalidation: "冲突快速缓和且商品与风险情绪同步修复",
        },
      ],
    },
    {
      id: "jin10-gs-rates-vol-20260326",
      date: "2026-03-26",
      title: "高盛：真正卡住风险资产的不是股市，是利率波动率",
      type: "Rates Vol",
      institution: "高盛",
      desk: "全球宏观策略",
      theme: "利率交易",
      quote: "只要利率波动率不稳，股票反弹也很难顺畅展开。",
      summary:
        "高盛认为市场开始对潜在谈判产生一定缓和预期，但真正制约全球风险资产的不是股市本身，而是利率和利率波动率。欧洲央行仍偏鹰、财政支出压力上升、债券拍卖偏弱，这一组合对债券并不友好，反而更利于黄金这类对冲资产。",
      takeaway:
        "先盯利率波动率是否稳定，再谈风险资产的持续修复。",
      conviction: 87,
      surprise: 79,
      divergence: 81,
      sourceId: 612176,
      signals: [
        {
          asset: "利率波动率",
          direction: "bullish",
          score: 87,
          horizon: "短中期",
          driver: "央行偏鹰、财政压力和拍卖疲弱同时存在，会让利率曲线继续维持高波动",
          expression: "优先盯利率波动，而不是急着追风险资产反弹",
          invalidation: "主要债券拍卖改善且通胀与政策预期同步降温",
        },
        {
          asset: "黄金",
          direction: "bullish",
          score: 79,
          horizon: "1-3月",
          driver: "高利率波动与财政风险并存时，黄金更适合作为组合对冲资产",
          expression: "黄金回撤仍按再定价后的配置窗口处理",
          invalidation: "实际利率持续上冲并压缩黄金对冲吸引力",
        },
        {
          asset: "美国10年期国债",
          direction: "bearish",
          score: 76,
          horizon: "短期",
          driver: "波动率上升与拍卖不稳会继续压制长债表现",
          expression: "长债先按高波动与偏弱框架处理",
          invalidation: "增长担忧迅速主导并重新带动长债避险买盘",
        },
      ],
    },
    {
      id: "jin10-gs-credit-mix-20260326",
      date: "2026-03-26",
      title: "高盛：高能源成本会让信用重新定价，欧洲比美元信用更脆弱",
      type: "Global Credit Trader",
      institution: "高盛",
      desk: "全球信用策略",
      theme: "信用交易",
      quote: "信用还没失控，但风险溢价会回到更不舒服的位置，欧洲先承压。",
      summary:
        "高盛认为在高能源成本持续更久的情形下，信用市场会面临更差的增长、通胀和政策组合，尤其欧洲信用会比美元信用承受更明显的风险溢价重建。杠杆贷款违约率会小幅抬升，但短期还不是全面失控，而是更典型的分化重定价。",
      takeaway:
        "信用不是立刻出事，而是要为更差的宏观组合重新补风险溢价。",
      conviction: 81,
      surprise: 75,
      divergence: 77,
      sourceId: 612228,
      signals: [
        {
          asset: "HY信用",
          direction: "bearish",
          score: 77,
          horizon: "1-3月",
          driver: "高能源成本与增长放缓会优先压缩高收益信用的风险承受力",
          expression: "HY 先按利差走阔和风险溢价回补来交易",
          invalidation: "能源价格快速回落且增长预期重新修复",
        },
        {
          asset: "杠杆贷款",
          direction: "bearish",
          score: 73,
          horizon: "1-3月",
          driver: "更高融资成本与较差增长组合会推高低质量借款人的违约压力",
          expression: "杠杆贷款继续要求更高风险补偿",
          invalidation: "违约预期和融资环境同步改善",
        },
        {
          asset: "美国IG信用",
          direction: "bullish",
          score: 68,
          horizon: "短中期",
          driver: "在美元与欧元信用之间，高盛更偏好美元信用的相对防御性",
          expression: "信用配置优先保留美元高等级而不是追欧洲信用修复",
          invalidation: "欧洲风险溢价明显收敛且能源冲击快速缓和",
        },
      ],
    },
    {
      id: "jin10-jpm-g10-fx-20260325",
      date: "2026-03-25",
      title: "摩根大通：G10 里先抱日元和离岸人民币，继续淡化英镑反弹",
      type: "G10 FX",
      institution: "摩根大通",
      desk: "全球外汇交易",
      theme: "外汇交易",
      quote: "这阶段更像 headline 驱动的拉锯市，反弹适合做减仓而不是追价。",
      summary:
        "摩根大通认为当前市场仍处在高度 headline 驱动的外汇环境，整体不适合重押单边观点，但组合上仍略偏向做空美元兑日元和离岸人民币，同时继续逢反弹做空英镑。欧元虽然表现比预期更稳，但在真正确认风险缓和前，仍不足以支撑积极追多。",
      takeaway:
        "G10 外汇先求防守和相对价值，不急着押单边风险偏好修复。",
      conviction: 80,
      surprise: 71,
      divergence: 74,
      sourceId: 612051,
      signals: [
        {
          asset: "日元",
          direction: "bullish",
          score: 82,
          horizon: "短期",
          driver: "不确定性仍高时，日元仍是更直接的避险相对价值表达",
          expression: "日元继续按防御性多头处理",
          invalidation: "停火与风险偏好修复显著压低避险需求",
        },
        {
          asset: "离岸人民币",
          direction: "bullish",
          score: 74,
          horizon: "短期",
          driver: "摩根大通倾向在美元反弹中继续卖出美元兑离岸人民币",
          expression: "离岸人民币更适合做相对价值修复，而不是追美元上行",
          invalidation: "亚洲风险快速恶化并重新带动美元全面走强",
        },
        {
          asset: "英镑",
          direction: "bearish",
          score: 76,
          horizon: "短期",
          driver: "滞胀式数据与风险事件交织时，英镑更像 headline 反弹中的卖出品种",
          expression: "英镑反弹继续以逢高减仓和做空为主",
          invalidation: "英国数据与风险偏好同步超预期改善",
        },
      ],
    },
    {
      id: "jin10-jpm-us-market-intell-20260325",
      date: "2026-03-25",
      title: "摩根大通：停火 headline 先压能源，但黄金和白银仍在继续被买",
      type: "US Market Intell",
      institution: "摩根大通",
      desk: "美国市场情报",
      theme: "宏观策略",
      quote: "油气会先交易缓和预期，但贵金属的强势说明避险需求还没真正退场。",
      summary:
        "摩根大通指出，关于停火和谈判的 headline 令风险资产短线反弹，油气价格和收益率回落，但黄金和白银依然维持更强走势，说明市场虽然在交易缓和预期，却并未完全撤掉避险仓位。",
      takeaway:
        "短线盘面开始给缓和定价，但真正的风险偏好修复还没有完全成立。",
      conviction: 79,
      surprise: 74,
      divergence: 72,
      sourceId: 612053,
      signals: [
        {
          asset: "黄金",
          direction: "bullish",
          score: 80,
          horizon: "短中期",
          driver: "在油气回落和美元持平的背景下仍然走强，说明黄金仍在承接避险与配置需求",
          expression: "黄金继续保留对冲仓位，不急着把缓和 headline 当成卖点",
          invalidation: "谈判取得实质进展并同步压低贵金属买盘",
        },
        {
          asset: "白银",
          direction: "bullish",
          score: 78,
          horizon: "短期",
          driver: "白银跟随贵金属板块继续被买，说明盘面对避险和再通胀两条线都未彻底放弃",
          expression: "白银继续按贵金属强势延续处理",
          invalidation: "风险偏好快速修复并带动贵金属整体回吐",
        },
        {
          asset: "原油",
          direction: "bearish",
          score: 73,
          horizon: "短期",
          driver: "停火与谈判 headline 会先压低最前线的能源风险溢价",
          expression: "原油短线先按 headline 回撤和风险溢价回吐看待",
          invalidation: "中东冲突重新升级并再度打断运输与供应",
        },
        {
          asset: "美国10年期国债",
          direction: "bullish",
          score: 69,
          horizon: "短期",
          driver: "风险缓和 headline 出现后，收益率先回落，说明久期短线重新获得一些支撑",
          expression: "长债短线按情绪修复窗口处理",
          invalidation: "油价重新上冲并再次带动通胀预期抬头",
        },
      ],
    },
    {
      id: "jin10-ubs-cio-alert-20260324",
      date: "2026-03-24",
      title: "瑞银：反弹是降风险窗口，不是重新追价的理由",
      type: "CIO Alert",
      institution: "瑞银",
      desk: "全球资产配置",
      theme: "宏观策略",
      quote: "地缘缓和能带来反弹，但还不足以把高能源成本和尾部波动一笔勾销。",
      summary:
        "瑞银认为特朗普推迟打击伊朗能源设施带来了风险资产反弹，但谈判基础仍然脆弱，能源流恢复不会平滑，投资者更应该趁反弹调整最怕高油价的暴露，而不是重新追逐风险。",
      takeaway:
        "先把反弹当成调仓窗口，而不是把地缘风险已经结束。",
      conviction: 84,
      surprise: 71,
      divergence: 76,
      sourceId: 611648,
      signals: [
        {
          asset: "欧洲股票",
          direction: "bearish",
          score: 78,
          horizon: "1-3月",
          driver: "高油价和高气价会压制欧洲制造业修复，并放大通胀与政策不确定性",
          expression: "降低顺周期欧洲风险暴露，先把欧洲从进攻腿拿下来",
          invalidation: "能源运输迅速恢复且欧洲增长预期重新回升",
        },
        {
          asset: "印度股票",
          direction: "bearish",
          score: 74,
          horizon: "1-3月",
          driver: "印度对进口能源依赖高，油价和 LNG 成本上行会同时压利润和外部平衡",
          expression: "反弹里优先减印度高 beta 仓位",
          invalidation: "油价快速回落并且外部融资压力显著缓解",
        },
        {
          asset: "瑞士股票",
          direction: "bullish",
          score: 68,
          horizon: "1-3月",
          driver: "防御属性、较稳定盈利和较低能源冲击暴露让瑞士市场更适合承接风险转移",
          expression: "用瑞士股票替代部分高弹性市场仓位",
          invalidation: "全球风险偏好全面修复并重回顺周期主线",
        },
        {
          asset: "短久期高等级债",
          direction: "bullish",
          score: 72,
          horizon: "短中期",
          driver: "更高收益率和更低久期敏感度，让短久期优质债在高波动环境下更适合做防守腿",
          expression: "把现金和高弹性权益的一部分切去短久期高等级债",
          invalidation: "利率继续快速上冲并显著压缩债券风险回报比",
        },
      ],
    },
    {
      id: "jin10-ubs-usd-20260324",
      date: "2026-03-24",
      title: "瑞银：美元近端还有支撑，但结构性逆风没有消失",
      type: "外汇交易员",
      institution: "瑞银",
      desk: "全球外汇策略",
      theme: "外汇交易",
      quote: "短线还是美元，长线别把全部货币篮子继续押在美元上。",
      summary:
        "瑞银认为中东冲突和能源价格上行仍会在近端支撑美元，但美国双赤字、全球美元资产配置过重和美联储换届预期意味着中长期的美元逆风并没有消失。",
      takeaway:
        "美元短线偏强，配置上却要开始减少过度美元化。",
      conviction: 81,
      surprise: 69,
      divergence: 73,
      sourceId: 611670,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 76,
          horizon: "短期",
          driver: "地缘风险、油价上行和美元流动性需求会在近端托住美元表现",
          expression: "美元短线继续偏多，但不要把它当成全年单边交易",
          invalidation: "谈判迅速落地并带动油价和避险需求同步回落",
        },
        {
          asset: "澳元",
          direction: "bullish",
          score: 71,
          horizon: "3-12月",
          driver: "美元结构性逆风仍在，而澳元受益于资源属性和更高票息环境",
          expression: "把近期回撤视作分批重建澳元仓位的窗口",
          invalidation: "中国和全球商品需求明显再走弱",
        },
        {
          asset: "人民币",
          direction: "bullish",
          score: 67,
          horizon: "3-12月",
          driver: "美元中长期弱化与政策稳定预期，使人民币在中期配置里更有修复空间",
          expression: "人民币以配置回补为主，不追短线波动",
          invalidation: "美元避险行情被进一步拉长且亚洲风险整体恶化",
        },
      ],
    },
    {
      id: "jin10-ubs-gold-20260324",
      date: "2026-03-24",
      title: "瑞银：黄金不是失效，而是在鹰派预期里被错杀",
      type: "贵金属专题",
      institution: "瑞银",
      desk: "全球贵金属策略",
      theme: "宏观策略",
      quote: "黄金的下跌更像是利率预期挤压，而不是长期对冲逻辑失效。",
      summary:
        "瑞银认为黄金近期回撤主要来自更高利率预期、美元走强和部分机构获利了结，但当前并不是类似 Volcker 或 Bernanke 式的政策转向，黄金仍是长期组合对冲工具，后续价格仍有上行空间。",
      takeaway:
        "别把这轮急跌当成黄金失去配置意义。",
      conviction: 85,
      surprise: 74,
      divergence: 79,
      sourceId: 611653,
      signals: [
        {
          asset: "黄金",
          direction: "bullish",
          score: 84,
          horizon: "6-12月",
          driver: "短期利率挤压释放后，去美元化、财政风险和中长期宏观对冲需求仍会重新支撑金价",
          expression: "黄金继续保留核心对冲仓，不把这轮回撤当成趋势反转",
          invalidation: "美联储真正进入持续紧缩并把实际利率稳定抬到更高平台",
        },
      ],
    },
    {
      id: "jin10-ubs-rates-20260324",
      date: "2026-03-24",
      title: "瑞银：债券近端先挨打，但年内反而更值得重新加回",
      type: "利率周报",
      institution: "瑞银",
      desk: "全球利率策略",
      theme: "利率交易",
      quote: "市场先把通胀冲击打满了，接下来更可能轮到增长和金融条件重新主导。",
      summary:
        "瑞银承认能源冲击会抬高近端收益率预测，但仍维持年内对高等级债偏多的判断，认为如果 disruption 持续，增长走弱和金融条件收紧最终会让债券恢复防御属性。",
      takeaway:
        "久期不是马上抄底，但更高收益率已经开始给年内做多债券提供入场点。",
      conviction: 82,
      surprise: 73,
      divergence: 75,
      sourceId: 611666,
      signals: [
        {
          asset: "美国10年期国债",
          direction: "bullish",
          score: 80,
          horizon: "到年末",
          driver: "市场已经快速把通胀冲击前置进价格，若增长和金融条件恶化，长债会重新获得支撑",
          expression: "用更高收益率逐步加回美国 10 年期国债",
          invalidation: "能源供给进一步受损并让通胀冲击明显超出当前定价",
        },
        {
          asset: "欧元区国债",
          direction: "bullish",
          score: 74,
          horizon: "1-3月",
          driver: "前端鹰派定价过快，若增长承压，欧债会比当前市场预期更早恢复防御性",
          expression: "欧债在高收益率位置分批重建久期",
          invalidation: "欧元区通胀二次扩散并迫使央行更鹰",
        },
        {
          asset: "美国TIPS",
          direction: "bullish",
          score: 72,
          horizon: "1-3月",
          driver: "在高通胀和低增长并存的环境下，TIPS 比普通国债更适合做防守补位",
          expression: "TIPS 作为滞胀环境下的保险腿增配",
          invalidation: "通胀预期快速塌陷并让通胀保护溢价消失",
        },
      ],
    },
    {
      id: "jin10-jpm-pandoras-bog-20260324",
      date: "2026-03-24",
      title: "摩根大通：真正危险的不是油价点位，而是 LNG 和库存链条被拉断",
      type: "能源专题",
      institution: "摩根大通",
      desk: "全球资产配置",
      theme: "能源冲击",
      quote: "别只盯油价，真正会把全球经济拖进痛区的是 LNG、库存和物流链条一起绷紧。",
      summary:
        "摩根大通认为全球能源强度虽然较历史下降，但一旦霍尔木兹持续受阻，真正的痛点会来自 LNG 和石化链条的缺口扩散，亚洲会最先遭遇配给与库存短缺，后续再向贸易和增长传导。",
      takeaway:
        "更该盯的是 LNG、库存天数和亚洲需求被迫压缩的速度，而不是只看油价绝对水平。",
      conviction: 87,
      surprise: 80,
      divergence: 82,
      sourceId: 611808,
      signals: [
        {
          asset: "LNG",
          direction: "bullish",
          score: 86,
          horizon: "1-3月",
          driver: "卡塔尔产能受损和替代供应不足，会把 LNG 定价压力向欧洲和亚洲同时扩散",
          expression: "能源链里优先盯 LNG，不只盯原油",
          invalidation: "霍尔木兹快速恢复通航且卡塔尔产能修复快于预期",
        },
        {
          asset: "亚洲股票",
          direction: "bearish",
          score: 73,
          horizon: "1-3月",
          driver: "亚洲会更早感受到燃料配给、库存短缺和成本冲击，对风险资产不利",
          expression: "亚洲顺周期和高能耗板块继续保守配置",
          invalidation: "能源配给没有扩大且亚洲需求端韧性超预期",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 78,
          horizon: "1-3月",
          driver: "海湾 LNG 缺口会迫使欧洲在边际上接受更高替代气价",
          expression: "欧洲气价继续按高波动高价格处理",
          invalidation: "欧洲快速锁定替代货源并压低现货紧张度",
        },
      ],
    },
    {
      id: "jin10-gs-us-equities-20260323",
      date: "2026-03-23",
      title: "高盛：美股只是去风险，还没到投降式出清",
      type: "交易台纪要",
      institution: "高盛",
      desk: "美国股票策略",
      theme: "股票策略",
      quote: "仓位的确在下，但离真正的投降式抛售还很远。",
      summary:
        "高盛认为美股已经出现更明显的脆弱信号，标普跌破 200 日均线且处于负 gamma 区，但当前仓位和超卖程度仍不足以说明市场已经完成出清。",
      takeaway:
        "风险释放了一部分，但还没到可以放心把回撤当成抄底终点的阶段。",
      conviction: 86,
      surprise: 72,
      divergence: 74,
      sourceId: 611492,
      signals: [
        {
          asset: "标普500",
          direction: "bearish",
          score: 84,
          horizon: "2-6周",
          driver: "跌破 200 日均线且负 gamma 放大双向波动，去风险过程还没有完成",
          expression: "继续保留对冲，不急着把回撤当成终局",
          invalidation: "超卖广度迅速扩散并出现明确的政策缓和信号",
        },
        {
          asset: "AI美股",
          direction: "bearish",
          score: 76,
          horizon: "短中期",
          driver: "AI 仍是仓位和盈利都未被彻底减掉的主要资金来源",
          expression: "把最拥挤的 AI 仓位当成对冲腿和资金来源",
          invalidation: "盈利预期重新上修且资金明显回流龙头",
        },
      ],
    },
    {
      id: "jin10-ms-boj-20260323",
      date: "2026-03-23",
      title: "摩根士丹利：日本央行没有放弃加息，但 4 月未必动手",
      type: "央行评述",
      institution: "摩根士丹利",
      desk: "日本宏观策略",
      theme: "利率交易",
      quote: "方向仍偏收紧，但节奏不再线性。",
      summary:
        "摩根士丹利认为日本央行仍维持加息倾向，但地缘风险会压低近端加息预期，基准情景仍是 4 月按兵不动、收益率曲线更陡。",
      takeaway:
        "政策正常化没有结束，只是近端交易要从直线押注改成节奏交易。",
      conviction: 78,
      surprise: 68,
      divergence: 73,
      sourceId: 611472,
      signals: [
        {
          asset: "日本国债",
          direction: "bearish",
          score: 74,
          horizon: "1-3月",
          driver: "政策倾向仍偏鹰，价格风险更多体现在长端与曲线陡化",
          expression: "回避日本长久期债券，优先看曲线陡化",
          invalidation: "油价冲击快速回落并显著压低日本通胀预期",
        },
        {
          asset: "日元",
          direction: "neutral",
          score: 58,
          horizon: "短期",
          driver: "近端加息预期回落与中期正常化预期互相抵消",
          expression: "日元先看震荡，不追单边",
          invalidation: "央行明确前置下一次加息时点",
        },
      ],
    },
    {
      id: "jin10-ms-energy-shock-20260322",
      date: "2026-03-22",
      title: "摩根士丹利：能源冲击正在向经济和市场传导",
      type: "全球宏观简报",
      institution: "摩根士丹利",
      desk: "全球宏观策略",
      theme: "能源冲击",
      quote: "先把能源当成成本冲击，而不只是商品行情。",
      summary:
        "摩根士丹利用情景分析讨论海湾事件后的能源冲击，核心判断是油价和 LNG 的供给扰动会同步抬升通胀、压低增长，并扩大市场结果分布。",
      takeaway:
        "油和 LNG 的上行，不只是商品交易，而是跨资产的再定价起点。",
      conviction: 84,
      surprise: 75,
      divergence: 77,
      sourceId: 611459,
      signals: [
        {
          asset: "原油",
          direction: "bullish",
          score: 82,
          horizon: "2-6周",
          driver: "地缘冲突直接收紧供应预期，现货紧张还会继续传导",
          expression: "能源方向优先保留多头暴露",
          invalidation: "运输通道恢复快于预期且供应重新释放",
        },
        {
          asset: "LNG",
          direction: "bullish",
          score: 80,
          horizon: "2-6周",
          driver: "中东 LNG 缺口短期缺少替代来源，全球气价会先被顶起",
          expression: "天然气与 LNG 比原油更容易出现供需错配",
          invalidation: "需求快速塌缩抵消供应缺口",
        },
        {
          asset: "全球股票",
          direction: "bearish",
          score: 68,
          horizon: "1-2月",
          driver: "成本冲击会先压缩风险资产估值并抬升贴现率",
          expression: "对高能源敏感板块维持防守",
          invalidation: "能源价格快速回落且央行转鸽",
        },
      ],
    },
    {
      id: "jin10-ms-hikes-overdone-20260322",
      date: "2026-03-22",
      title: "摩根士丹利：市场对重新加息的恐惧可能过度",
      type: "利率周报",
      institution: "摩根士丹利",
      desk: "美国利率策略",
      theme: "利率交易",
      quote: "不是不鹰，而是市场把更久更高的定价走得太快。",
      summary:
        "摩根士丹利上修了通胀、下修了增长与就业，但仍坚持 2026 年会有两次降息，认为市场把油价冲击过度解读成重新加息。",
      takeaway:
        "短端最极端的鹰派定价并不稳固，真正的终局仍更接近晚一点的降息。",
      conviction: 82,
      surprise: 71,
      divergence: 79,
      sourceId: 611460,
      signals: [
        {
          asset: "美债2年",
          direction: "bullish",
          score: 73,
          horizon: "1-2月",
          driver: "市场把加息风险打得过满，与 MS 的 Fed 路径存在偏差",
          expression: "前端利率回调后更适合逢高配债",
          invalidation: "能源冲击二次抬升核心通胀并迫使联储更鹰",
        },
        {
          asset: "美债10年",
          direction: "neutral",
          score: 61,
          horizon: "中期",
          driver: "增长转弱与通胀粘性在长端互相对冲",
          expression: "长端先看区间，不急着单边押注",
          invalidation: "财政与油价共同推动期限溢价继续扩张",
        },
      ],
    },
    {
      id: "jin10-ms-lng-standstill-20260322",
      date: "2026-03-22",
      title: "摩根士丹利：LNG 仍停在僵局里，缺口还没被填平",
      type: "能源专题",
      institution: "摩根士丹利",
      desk: "全球能源策略",
      theme: "能源冲击",
      quote: "只要中东 LNG 还没恢复，市场就会越走越缺。",
      summary:
        "摩根士丹利认为中东 LNG 供应停摆接近三周，需求虽有回落但远不足以填平供给缺口，如果短期内没有解决，天然气市场会进一步走向赤字。",
      takeaway:
        "LNG 不解决，能源冲击就不会轻易退潮。",
      conviction: 87,
      surprise: 74,
      divergence: 72,
      sourceId: 611461,
      signals: [
        {
          asset: "LNG",
          direction: "bullish",
          score: 85,
          horizon: "2-8周",
          driver: "供给恢复无时间表且需求下滑不足以平衡缺口",
          expression: "优先做多 LNG 与天然气价格弹性",
          invalidation: "中东 LNG 航道与出口恢复快于预期",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 77,
          horizon: "短中期",
          driver: "欧洲最容易承接全球 LNG 再定价和库存焦虑",
          expression: "欧洲气价是最直接的外溢表达",
          invalidation: "欧洲库存与替代来源缓冲超预期",
        },
      ],
    },
    {
      id: "jin10-ms-inflation-vs-growth-20260322",
      date: "2026-03-22",
      title: "摩根士丹利：通胀和增长正在重新争夺主导权",
      type: "全球宏观周报",
      institution: "摩根士丹利",
      desk: "全球宏观策略",
      theme: "宏观策略",
      quote: "眼下先主导市场的是通胀，后面才轮到增长反击。",
      summary:
        "摩根士丹利认为央行本周面对油价冲击时明显偏向通胀风险，发达市场前端利率的抛压说明市场还在用更鹰的方式重估成本冲击。",
      takeaway:
        "近端先盯通胀定价，后面再看增长是否会把行情反杀回来。",
      conviction: 79,
      surprise: 69,
      divergence: 70,
      sourceId: 611464,
      signals: [
        {
          asset: "发达市场前端利率",
          direction: "bearish",
          score: 75,
          horizon: "短中期",
          driver: "央行对通胀风险更敏感，前端先承受重定价",
          expression: "保持前端防守，不急着逆势接多",
          invalidation: "冲击被界定为暂时性且央行转向忽略",
        },
        {
          asset: "黄金",
          direction: "bullish",
          score: 64,
          horizon: "波段",
          driver: "一旦增长转弱开始压过通胀，黄金更容易重获相对优势",
          expression: "黄金更适合做第二阶段防御",
          invalidation: "实际利率持续抬升并压制避险需求",
        },
      ],
    },
    {
      id: "jin10-gs-iran-topofmind-20260321",
      date: "2026-03-21",
      title: "高盛：真正的问题是伊朗冲突会拖多久、会坏到什么程度",
      type: "Top of Mind",
      institution: "高盛",
      desk: "全球宏观策略",
      theme: "能源冲击",
      quote: "现在的关键变量不是方向，而是冲突持续时间。",
      summary:
        "高盛把伊朗冲突定义为历史级能源供应冲击，并强调持续时间与传导路径将决定全球经济和市场的最终损伤。",
      takeaway:
        "地缘风险定价现在更像期限和路径问题，而不只是一次性冲击。",
      conviction: 88,
      surprise: 79,
      divergence: 81,
      sourceId: 611419,
      signals: [
        {
          asset: "原油波动率",
          direction: "bullish",
          score: 86,
          horizon: "短线",
          driver: "持续时间不确定会抬高尾部风险定价",
          expression: "优先用波动率而不是单向追价表达风险",
          invalidation: "冲突快速降级并出现稳定停火预期",
        },
        {
          asset: "黄金",
          direction: "bullish",
          score: 72,
          horizon: "1-2月",
          driver: "地缘风险和滞胀担忧共同支撑避险需求",
          expression: "黄金作为跨市场缓冲层保留底仓",
          invalidation: "能源冲击明显缓和且实际利率再度上行",
        },
        {
          asset: "欧洲股票",
          direction: "bearish",
          score: 67,
          horizon: "1-2月",
          driver: "能源输入型区域更先承受利润率压力",
          expression: "回避欧洲高能源敏感板块",
          invalidation: "欧洲财政对冲力度显著超预期",
        },
      ],
    },
    {
      id: "jin10-gs-equity-radar-20260321",
      date: "2026-03-21",
      title: "高盛：滞胀风险、能源资本开支和政策重新决定股票主线",
      type: "周度总览",
      institution: "高盛",
      desk: "全球股票策略",
      theme: "股票策略",
      quote: "现在不是全面撤退，而是从 beta 切到质量与资源投资链。",
      summary:
        "高盛认为当前并非全面熊市，但股市仍面临进一步回撤风险；在 60/40 组合里，更应偏向防御、质量和少量相对安全资产，同时关注能源资本开支加速的赢家。",
      takeaway:
        "全面 risk-off 还没必要，但股票端的领导权正在从高 beta 转向质量和资源链。",
      conviction: 83,
      surprise: 73,
      divergence: 76,
      sourceId: 611404,
      signals: [
        {
          asset: "黄金",
          direction: "bullish",
          score: 71,
          horizon: "1-3月",
          driver: "防御资产在滞胀框架下重新获得组合价值",
          expression: "黄金承担多资产组合缓冲",
          invalidation: "增长快速修复且油价明显回落",
        },
        {
          asset: "能源股",
          direction: "bullish",
          score: 76,
          horizon: "1-2季",
          driver: "能源资本开支加速会把需求传到设备和服务链",
          expression: "在资源链里找 capex 受益者",
          invalidation: "油气公司重新缩减资本开支",
        },
        {
          asset: "全球股票",
          direction: "bearish",
          score: 66,
          horizon: "短中期",
          driver: "估值起点与地缘风险组合仍不友好",
          expression: "控制组合回撤，优先质量因子",
          invalidation: "政策和盈利同时改善",
        },
      ],
    },
    {
      id: "jin10-gs-fx-trader-20260321",
      date: "2026-03-21",
      title: "高盛：美元下行的飞行路径被打断了",
      type: "外汇交易员",
      institution: "高盛",
      desk: "全球外汇策略",
      theme: "外汇交易",
      quote: "美元空头的节奏被打断，先别把下行趋势想得太顺。",
      summary:
        "高盛认为如果中东冲击只是短期扰动，年初压制美元的因素仍会回来；但如果能源与避险链条持续，美元会重新获得支持。",
      takeaway:
        "美元下行趋势没有被完全推翻，但短期防御阶段已经回来了。",
      conviction: 80,
      surprise: 70,
      divergence: 77,
      sourceId: 611407,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 78,
          horizon: "2-6周",
          driver: "避险需求和能源冲击会暂时逆转年初的美元回落逻辑",
          expression: "美元重新作为防御腿配置",
          invalidation: "能源市场快速正常化并带动风险偏好修复",
        },
        {
          asset: "离岸人民币",
          direction: "bearish",
          score: 68,
          horizon: "短中期",
          driver: "美元反弹与能源输入压力共同压制亚洲货币",
          expression: "人民币和北亚货币先做防守",
          invalidation: "美元重新转弱且中国增长预期改善",
        },
        {
          asset: "瑞郎",
          direction: "bullish",
          score: 64,
          horizon: "短线",
          driver: "避险偏好回升时瑞郎表现更稳健",
          expression: "风险事件阶段保留瑞郎避险敞口",
          invalidation: "地缘风险快速降温",
        },
      ],
    },
    {
      id: "jin10-gs-rates-trader-20260321",
      date: "2026-03-21",
      title: "高盛：眼下主导利率市场的，还是通胀，不是增长",
      type: "利率交易员",
      institution: "高盛",
      desk: "全球利率策略",
      theme: "利率交易",
      quote: "先尊重通胀抬头，再等待增长把行情拉回来。",
      summary:
        "高盛认为央行的鹰派冲动把前端利率推高，但市场对终点利率的上修仍和真实冲击性质不完全匹配，在外部缓和或更明显的增长下行出现前，利率端仍需谨慎。",
      takeaway:
        "近端尊重更高利率，别太早去赌增长交易会立刻接管。",
      conviction: 82,
      surprise: 71,
      divergence: 75,
      sourceId: 611408,
      signals: [
        {
          asset: "美债10年",
          direction: "bearish",
          score: 77,
          horizon: "短中期",
          driver: "通胀担忧和期限溢价共同压制长端",
          expression: "长端先不抄底，警惕继续走熊平",
          invalidation: "冲突降级并明显触发增长担忧",
        },
        {
          asset: "利率波动率",
          direction: "bullish",
          score: 69,
          horizon: "短线",
          driver: "市场缺少让压力持续缓解的外部机制",
          expression: "回避卖波动和纯 carry 交易",
          invalidation: "央行与油价同时回稳",
        },
      ],
    },
    {
      id: "jin10-citi-ny-open-20260320",
      date: "2026-03-20",
      title: "花旗：市场像在烧最后一点燃料，美元和油价一起压制高 beta",
      type: "纽约盘前",
      institution: "花旗",
      desk: "G10 外汇策略",
      theme: "外汇交易",
      quote: "市场不是没在动，而是在透支最后一点燃料。",
      summary:
        "花旗认为在伦敦盘中美元升势重新加速，高 beta 货币承压，油价继续抬升让亚洲货币和风险偏好都处在更脆弱的位置。",
      takeaway:
        "美元走强和油价抬升同时发生时，最先掉队的是高 beta 货币。",
      conviction: 76,
      surprise: 65,
      divergence: 68,
      sourceId: 611370,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 74,
          horizon: "短线",
          driver: "美债偏弱与欧洲固收承压共同推升美元",
          expression: "美元盘中强势阶段继续做防守",
          invalidation: "油价与收益率同时回落",
        },
        {
          asset: "高beta货币",
          direction: "bearish",
          score: 72,
          horizon: "短线",
          driver: "风险事件下伦敦时段资金更倾向回流美元",
          expression: "回避高 beta 外汇顺周期多头",
          invalidation: "风险事件降温且资金回流风险资产",
        },
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 66,
          horizon: "短线",
          driver: "伊朗相关消息与炼厂动态持续支撑油价",
          expression: "油价仍是扰动外汇的外生变量",
          invalidation: "地缘消息被快速证伪",
        },
      ],
    },
    {
      id: "jin10-bofa-flow-show-20260320",
      date: "2026-03-20",
      title: "美银：真正的痛感还在后面，资产领导权正在换挡",
      type: "资金流观察",
      institution: "美银",
      desk: "全球资产配置",
      theme: "资金流向",
      quote: "市场不会在投资者慌张时见底，往往在政策制定者慌张时才会。",
      summary:
        "美银把 2020 年代下半段概括为商品牛扩散、制造业与基础设施重估，以及债券与美元在错误位置的再平衡；策略层面建议逢高卖美元、5% 附近买 30 年美债、标普 6600 以下再考虑接回。",
      takeaway:
        "真正的重点不是追最热资产，而是提前站到下一轮资产领导权切换的一侧。",
      conviction: 81,
      surprise: 78,
      divergence: 80,
      sourceId: 611354,
      signals: [
        {
          asset: "美元",
          direction: "bearish",
          score: 70,
          horizon: "1-3月",
          driver: "美元指数站上 100 之后更接近被高位卖出而不是继续追涨",
          expression: "美元高位减仓，不追尾段强势",
          invalidation: "全球风险快速恶化触发再一轮避险美元买盘",
        },
        {
          asset: "30年美债",
          direction: "bullish",
          score: 75,
          horizon: "波段",
          driver: "长端收益率冲到 5% 附近更接近价值区间",
          expression: "长债等更高收益率再分批接回",
          invalidation: "通胀二次上冲且财政失控",
        },
        {
          asset: "大宗商品",
          direction: "bullish",
          score: 72,
          horizon: "中期",
          driver: "地缘与供应链重构会把商品牛从黄金扩散到金属和能源",
          expression: "商品配置从单一黄金转向更广泛资源链",
          invalidation: "供给约束明显缓解",
        },
      ],
    },
    {
      id: "jin10-jpm-oil-flash-20260320",
      date: "2026-03-20",
      title: "摩根大通：高油价已经开始压缩亚洲真实需求",
      type: "油市快报",
      institution: "摩根大通",
      desk: "全球大宗商品",
      theme: "能源冲击",
      quote: "这轮油价冲击已经从盘面走进了亚洲的出行和工业活动。",
      summary:
        "摩根大通观察到亚洲成品油流向和航煤需求显著走弱，柴油已成为最直接的瓶颈，多国通过假期提前、四天工作周、远程办公和燃油附加费来压缩需求。",
      takeaway:
        "当需求管理开始落地，高油价就不再只是商品行情，而会直连增长和消费。",
      conviction: 84,
      surprise: 77,
      divergence: 76,
      sourceId: 611310,
      signals: [
        {
          asset: "亚洲航空股",
          direction: "bearish",
          score: 71,
          horizon: "2-6周",
          driver: "航煤逼近 200 美元/桶使多条航线失去经济性",
          expression: "回避对燃油敏感的出行链",
          invalidation: "航油价格迅速回落",
        },
        {
          asset: "柴油",
          direction: "bullish",
          score: 78,
          horizon: "短中期",
          driver: "柴油成为当前最紧的真实瓶颈，价格会先于其他成品油维持强势",
          expression: "关注柴油与炼化链的现货紧张",
          invalidation: "应急供应大规模释放",
        },
        {
          asset: "亚洲需求股",
          direction: "bearish",
          score: 69,
          horizon: "1-2月",
          driver: "需求管理和节能措施会压制可选消费与运输活动",
          expression: "亚洲内需链先做防守",
          invalidation: "能源供应恢复并取消限制措施",
        },
      ],
    },
    {
      id: "jin10-gs-boe-20260320",
      date: "2026-03-20",
      title: "高盛：英国央行虽然没动，但口风已经明显转鹰",
      type: "央行评述",
      institution: "高盛",
      desk: "英国宏观策略",
      theme: "利率交易",
      quote: "按兵不动不等于安全，英国前端利率还有再定价空间。",
      summary:
        "高盛认为英国央行 3 月以 9 比 0 维持利率不变，但强调如果中东冲击更大或更久，政策就需要更紧。",
      takeaway:
        "这不是一次鸽派按兵不动，而是给更高更久预留了口子。",
      conviction: 80,
      surprise: 69,
      divergence: 74,
      sourceId: 611259,
      signals: [
        {
          asset: "英国前端利率",
          direction: "bearish",
          score: 79,
          horizon: "2-6周",
          driver: "央行明确把更大更久的能源冲击纳入收紧条件",
          expression: "英国前端继续保持防守",
          invalidation: "能源冲击迅速缓和并带动通胀预期回落",
        },
        {
          asset: "英镑",
          direction: "bullish",
          score: 61,
          horizon: "短中期",
          driver: "相对更鹰的政策口径给英镑提供一定支撑",
          expression: "英镑只做政策差，不做风险偏好",
          invalidation: "英国增长下行快于预期",
        },
      ],
    },
    {
      id: "jin10-gs-credit-trader-20260320",
      date: "2026-03-20",
      title: "高盛：信用基本面还行，但技术面已经开始变坏",
      type: "信用交易员",
      institution: "高盛",
      desk: "全球信用策略",
      theme: "信用交易",
      quote: "信用不一定马上出事，但技术面已经不支持继续安心吃 carry。",
      summary:
        "高盛认为北美 IG 企业基本面仍稳，但一级市场供应沉重、波动抬升和新券让利扩大，说明信用市场正在面对更不友好的技术面组合。",
      takeaway:
        "当前信用市场最需要提防的不是盈利，而是供给、波动和流动性同时变差。",
      conviction: 79,
      surprise: 66,
      divergence: 72,
      sourceId: 611267,
      signals: [
        {
          asset: "美国IG信用",
          direction: "bearish",
          score: 73,
          horizon: "1-3月",
          driver: "供给拥挤与波动上升推高新券让利和二级压力",
          expression: "降低纯 carry 仓位，等待更好补偿",
          invalidation: "发行供给迅速收缩并且波动回落",
        },
        {
          asset: "HY信用",
          direction: "bearish",
          score: 68,
          horizon: "短中期",
          driver: "技术面转坏会先伤到低质量信用",
          expression: "高收益信用保持谨慎",
          invalidation: "风险偏好快速修复",
        },
      ],
    },
    {
      id: "jin10-gs-goal-positioning-20260324",
      date: "2026-03-24",
      title: "高盛：仓位轮动还在继续，能源股吸金，长久期债承压",
      type: "仓位观察",
      institution: "高盛",
      desk: "全球资产配置",
      theme: "资金流向",
      quote: "资金不是简单离场，而是在能源、防守和短久期之间重新站位。",
      summary:
        "高盛在 GOAL Positioning 中指出，近期全球资金继续从贷款、金融股和长久期债撤出，能源股成为少数仍在吸引净流入的周期板块，短久期政府债的承接明显强于长久期。",
      takeaway:
        "当前更像轮动式去风险，不是全面无差别抛售。",
      conviction: 83,
      surprise: 74,
      divergence: 77,
      sourceId: 611608,
      signals: [
        {
          asset: "能源股",
          direction: "bullish",
          score: 81,
          horizon: "1-3月",
          driver: "地缘冲击和更高油气价格把现金流重新推回能源板块",
          expression: "能源继续作为周期里少数能承接增量资金的方向",
          invalidation: "油气供应快速恢复并压回能源价格",
        },
        {
          asset: "英国长久期国债",
          direction: "bearish",
          score: 72,
          horizon: "短中期",
          driver: "长久期 Gilts 录得显著流出，资金更偏短久期安全资产",
          expression: "久期暴露继续收短，不急着抄长端",
          invalidation: "增长担忧重新压倒通胀担忧",
        },
        {
          asset: "全球金融股",
          direction: "bearish",
          score: 69,
          horizon: "1-3月",
          driver: "风险偏好回落和信贷担忧让金融股持续失血",
          expression: "金融股先按资金外流逻辑处理",
          invalidation: "信用利差回落且风险偏好明显修复",
        },
      ],
    },
    {
      id: "jin10-jpm-us-market-intell-20260319",
      date: "2026-03-19",
      title: "摩根大通：标普目标下修到 7200，跌破关键位后支撑要看 6000-6200",
      type: "美国晨会",
      institution: "摩根大通",
      desk: "美国股票策略",
      theme: "股票策略",
      quote: "在油价冲击没有被真正消化前，美股还没到可以放心接飞刀的时候。",
      summary:
        "摩根大通在美国市场晨报中下调年末标普 500 目标至 7200，并提醒若指数在 200 日均线下方持续失守，下一道更强支撑可能要到 6000-6200 区间才会出现。",
      takeaway:
        "对美股的态度仍是战术偏空，关键不是估值便宜，而是油价冲击是否继续放大。",
      conviction: 85,
      surprise: 79,
      divergence: 78,
      sourceId: 611081,
      signals: [
        {
          asset: "标普500",
          direction: "bearish",
          score: 84,
          horizon: "1-3月",
          driver: "油价冲击与 200 日均线失守叠加，压低风险偏好和仓位容忍度",
          expression: "标普跌破关键位后继续按战术偏空处理",
          invalidation: "油气价格快速回落且指数重新站回关键均线",
        },
        {
          asset: "罗素2000",
          direction: "bearish",
          score: 76,
          horizon: "短中期",
          driver: "小盘股对增长、融资和波动环境更敏感",
          expression: "小盘和高杠杆成长先保持防守",
          invalidation: "增长预期回升并带动小盘重新跑赢",
        },
        {
          asset: "VIX",
          direction: "bullish",
          score: 72,
          horizon: "短线",
          driver: "能源冲击和政策不确定性会让股票波动率维持更高平台",
          expression: "保留权益对冲，不急着卖波动",
          invalidation: "风险事件快速降温并让波动率回落",
        },
      ],
    },
    {
      id: "jin10-jpm-intl-market-intell-20260319",
      date: "2026-03-19",
      title: "摩根大通：真正拖后腿的是欧洲，气价飙升让风险偏好重新下台阶",
      type: "国际晨会",
      institution: "摩根大通",
      desk: "全球宏观策略",
      theme: "宏观策略",
      quote: "油还不是全部，欧洲天然气才是让全球风险资产重新分层的那根针。",
      summary:
        "摩根大通在国际晨报中称，南帕尔斯和卡塔尔 Ras Laffan 遭袭后，全球能源供应风险重新升级，布伦特升破 113 美元，欧洲因天然气大涨而明显跑输。",
      takeaway:
        "国际盘面上最脆弱的不是所有风险资产，而是最先承受气价冲击的欧洲。",
      conviction: 83,
      surprise: 76,
      divergence: 74,
      sourceId: 611080,
      signals: [
        {
          asset: "欧洲股票",
          direction: "bearish",
          score: 79,
          horizon: "1-3月",
          driver: "欧洲率先承受天然气飙升对增长和盈利的挤压",
          expression: "欧洲权益先按高能价压缩利润来定价",
          invalidation: "气价快速回落且替代供应加速到位",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 83,
          horizon: "短中期",
          driver: "中东气源受损让欧洲不得不以更高价格争夺替代货源",
          expression: "把欧洲气价继续当成高波动高价格资产",
          invalidation: "卡塔尔和霍尔木兹供应恢复快于预期",
        },
        {
          asset: "布伦特原油",
          direction: "bullish",
          score: 76,
          horizon: "短线",
          driver: "油气供应担忧在冲突升级后重新推高风险溢价",
          expression: "原油维持高位震荡思路，不轻易逆势做空",
          invalidation: "地缘风险降温并恢复更多旁路运输",
        },
      ],
    },
    {
      id: "jin10-citi-lng-open-20260319",
      date: "2026-03-19",
      title: "花旗：卡塔尔 LNG 受损后，市场先交易的是气价和美元，不是数据",
      type: "纽约盘前",
      institution: "花旗",
      desk: "G10 外汇策略",
      theme: "外汇交易",
      quote: "在 LNG 设施受损之后，宏观数据和央行会议都得先给能源消息让路。",
      summary:
        "花旗指出，卡塔尔 Ras Laffan LNG 设施传出严重受损后，市场风险情绪显著转负，天然气飙升拖累全球固收，美元与能源相关价格重新成为盘面主导。",
      takeaway:
        "能源供给消息一旦升级，外汇和利率都会先围着气价与美元转。",
      conviction: 82,
      surprise: 77,
      divergence: 75,
      sourceId: 611078,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 71,
          horizon: "短线",
          driver: "风险情绪转弱与天然气冲击同步抬高美元需求",
          expression: "美元在能源冲击升级时继续做第一层对冲",
          invalidation: "能源设施受损被证伪且风险偏好快速修复",
        },
        {
          asset: "高beta货币",
          direction: "bearish",
          score: 74,
          horizon: "短线",
          driver: "外部风险升温会先打压依赖风险偏好的高 beta 货币",
          expression: "高 beta 外汇继续回避顺周期多头",
          invalidation: "全球风险资产重新获得增量资金",
        },
        {
          asset: "LNG",
          direction: "bullish",
          score: 82,
          horizon: "1-3月",
          driver: "Ras Laffan 受损意味着全球 LNG 供给缺口可能持续数周甚至更久",
          expression: "气价链继续按供给缺口扩散来交易",
          invalidation: "卡塔尔产能恢复时间显著提前",
        },
      ],
    },
    {
      id: "jin10-gs-oil-tracker-20260319",
      date: "2026-03-19",
      title: "高盛：能源设施风险在上升，霍尔木兹流量仍远低于正常",
      type: "油市跟踪",
      institution: "高盛",
      desk: "全球大宗商品",
      theme: "能源冲击",
      quote: "市场开始把能源设施本身纳入定价，而不只是盯运输通道。",
      summary:
        "高盛在 Oil Tracker 中指出，伊朗南帕尔斯气田、沙特炼化和卡塔尔 LNG 相关设施面临更高攻击风险，霍尔木兹流量仍处低位，能源市场开始同时定价供应链和基础设施风险。",
      takeaway:
        "这一轮不是单纯的油轮风险，而是能源基础设施也在进入溢价。",
      conviction: 84,
      surprise: 79,
      divergence: 78,
      sourceId: 611009,
      signals: [
        {
          asset: "原油",
          direction: "bullish",
          score: 80,
          horizon: "短中期",
          driver: "运输与基础设施双重风险把原油风险溢价继续抬高",
          expression: "原油继续按供给风险上修来处理",
          invalidation: "霍尔木兹恢复通航并且设施修复快于预期",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 78,
          horizon: "1-3月",
          driver: "卡塔尔和海湾设施风险会传导到欧洲替代气定价",
          expression: "欧洲天然气保持高波动高价格的交易框架",
          invalidation: "替代货源快速补足且库存担忧缓解",
        },
        {
          asset: "LNG",
          direction: "bullish",
          score: 79,
          horizon: "1-3月",
          driver: "全球 LNG 主产区设施受损显著提高现货再平衡难度",
          expression: "LNG 继续按紧平衡链条处理",
          invalidation: "中东设施受损被控制在局部范围",
        },
      ],
    },
    {
      id: "jin10-gs-fx-hedges-20260319",
      date: "2026-03-19",
      title: "高盛：更大的能源价格冲击下，美元和日元仍是最直接的外汇对冲",
      type: "外汇策略",
      institution: "高盛",
      desk: "全球外汇策略",
      theme: "外汇交易",
      quote: "如果冲击继续加大，市场最后还是会回到美元和日元的避险组合。",
      summary:
        "高盛认为自伊朗冲突爆发以来，贸易加权美元已上行约 2%，外汇相对表现与各国贸易条件变化高度相关；若衰退担忧再上一个台阶，日元会比高 beta 货币更先获得保护性买盘。",
      takeaway:
        "更大的能源冲击下，外汇对冲还是优先选美元和日元，而不是赌高 beta 反弹。",
      conviction: 82,
      surprise: 72,
      divergence: 73,
      sourceId: 610938,
      signals: [
        {
          asset: "美元",
          direction: "bullish",
          score: 79,
          horizon: "短中期",
          driver: "能源冲击放大了美元在贸易条件和流动性层面的相对优势",
          expression: "美元继续作为第一层宏观对冲",
          invalidation: "油价快速回落并削弱避险需求",
        },
        {
          asset: "日元",
          direction: "bullish",
          score: 74,
          horizon: "短线",
          driver: "衰退担忧升温后，日元更容易从风险资产撤退中受益",
          expression: "日元作为更纯粹的风险对冲仓位回补",
          invalidation: "全球风险情绪重新修复并压制避险需求",
        },
        {
          asset: "澳元",
          direction: "bearish",
          score: 70,
          horizon: "短中期",
          driver: "高 beta 商品货币在衰退担忧抬头时更容易被先卖出",
          expression: "澳元反弹先看作减仓窗口",
          invalidation: "商品需求改善且风险偏好重新回升",
        },
      ],
    },
    {
      id: "jin10-gs-fomc-preview-20260318",
      date: "2026-03-18",
      title: "高盛：联储面前不是单向通胀，而是降息和延后之间的双向风险",
      type: "FOMC前瞻",
      institution: "高盛",
      desk: "美国宏观策略",
      theme: "利率交易",
      quote: "战争抬高了通胀，也抬高了更早降息的尾部风险。",
      summary:
        "高盛在 3 月 FOMC 前瞻中上修了年底 PCE 预测、下修增长并上修失业率，认为伊朗战争让联储同时面对更高通胀与更弱增长，近期更可能按兵不动，但双向政策风险都被抬高。",
      takeaway:
        "利率市场不能只盯通胀或只盯衰退，联储现在面对的是两头都更难。",
      conviction: 80,
      surprise: 74,
      divergence: 77,
      sourceId: 610807,
      signals: [
        {
          asset: "美债10年",
          direction: "bearish",
          score: 71,
          horizon: "短中期",
          driver: "能源冲击抬高通胀补偿并延缓市场对降息的前置定价",
          expression: "长端先按更高更久的利率环境来处理",
          invalidation: "增长担忧迅速压倒通胀预期",
        },
        {
          asset: "利率波动率",
          direction: "bullish",
          score: 64,
          horizon: "短线",
          driver: "双向政策风险让市场更难用单一路径去给联储定价",
          expression: "利率端保留波动保护，不做单边低波假设",
          invalidation: "联储明确给出更单一的政策信号",
        },
      ],
    },
    {
      id: "jin10-ms-fomc-preview-20260318",
      date: "2026-03-18",
      title: "摩根士丹利：油价冲击下，联储的剧本还是按兵不动或更早降息，不是加息",
      type: "FOMC前瞻",
      institution: "摩根士丹利",
      desk: "美国利率策略",
      theme: "利率交易",
      quote: "油价能抬升通胀，但还没改变联储先等、必要时再救增长的框架。",
      summary:
        "摩根士丹利认为油价冲击不会把联储的选项推向加息，相反政策路径仍是按兵不动或在增长恶化时更早降息，市场对重新加息的担忧可能高估。",
      takeaway:
        "别把油价冲击机械翻译成重新加息。",
      conviction: 83,
      surprise: 76,
      divergence: 81,
      sourceId: 610810,
      signals: [
        {
          asset: "美债2年",
          direction: "bullish",
          score: 70,
          horizon: "1-3月",
          driver: "若增长承压快于通胀扩散，前端收益率会率先回落",
          expression: "前端利率更适合布局重新交易降息的窗口",
          invalidation: "通胀二次扩散明显超出联储容忍区间",
        },
        {
          asset: "美债10年",
          direction: "neutral",
          score: 57,
          horizon: "短中期",
          driver: "长端一边受通胀抬升影响，一边受增长担忧支撑，方向更容易拉锯",
          expression: "长端不做极端单边，先接受震荡区间",
          invalidation: "油价或增长预期明显单边突破",
        },
      ],
    },
    {
      id: "jin10-ms-global-gas-lng-20260316",
      date: "2026-03-16",
      title: "摩根士丹利：LNG 市场经不起更久的卡塔尔中断",
      type: "全球燃气专题",
      institution: "摩根士丹利",
      desk: "全球大宗商品",
      theme: "能源冲击",
      quote: "卡塔尔一旦停得更久，2026 年原本的宽松就会被彻底吃掉。",
      summary:
        "摩根士丹利指出，若卡塔尔供应中断维持 3-4 周，LNG 市场原本预计的年度盈余将被大幅侵蚀；一旦超过一个月，市场会从宽松直接转入缺口。",
      takeaway:
        "这不是短线情绪交易，供给中断时间一旦拉长，LNG 供需表会被真正改写。",
      conviction: 86,
      surprise: 81,
      divergence: 82,
      sourceId: 610652,
      signals: [
        {
          asset: "LNG",
          direction: "bullish",
          score: 80,
          horizon: "1-3月",
          driver: "卡塔尔供给损失会迅速侵蚀全年盈余并把市场推向缺口",
          expression: "LNG 继续按供给缺口扩大的逻辑处理",
          invalidation: "中断时间被压缩到数周内且替代货源充足",
        },
        {
          asset: "欧洲天然气",
          direction: "bullish",
          score: 73,
          horizon: "短中期",
          driver: "欧洲被迫以更高价格争夺替代货源来弥补卡塔尔缺口",
          expression: "欧洲气价继续维持高波动多头框架",
          invalidation: "欧洲快速锁定更多替代 LNG 进口",
        },
      ],
    },
    {
      id: "jin10-ms-oil-consumer-20260316",
      date: "2026-03-16",
      title: "摩根士丹利：持续油价冲击会先伤可选消费和受约束家庭",
      type: "美国宏观评述",
      institution: "摩根士丹利",
      desk: "美国宏观策略",
      theme: "宏观策略",
      quote: "真正先感到痛的，不是总消费，而是被油价和信贷同时挤压的那部分家庭。",
      summary:
        "摩根士丹利认为若油价冲击持续，将首先拖累商品消费和信用受限家庭支出，可选消费链会比整体经济更早感到压力。",
      takeaway:
        "盯住可选消费和低收入家庭支出，比盯总量数据更能提前看到冲击。",
      conviction: 79,
      surprise: 72,
      divergence: 74,
      sourceId: 610653,
      signals: [
        {
          asset: "美国可选消费",
          direction: "bearish",
          score: 74,
          horizon: "1-3月",
          driver: "持续更高的油价会先挤压非必需品消费和出行相关支出",
          expression: "可选消费先按利润和需求双压来处理",
          invalidation: "油价回落并恢复居民实际购买力",
        },
        {
          asset: "低收入家庭支出",
          direction: "bearish",
          score: 69,
          horizon: "短中期",
          driver: "油价与信贷成本同步上行会率先压缩受约束家庭的消费空间",
          expression: "先观察低收入客群暴露更高的零售链",
          invalidation: "能源补贴或收入改善抵消成本压力",
        },
      ],
    },
    {
      id: "jin10-ms-private-credit-20260316",
      date: "2026-03-16",
      title: "摩根士丹利：私募信贷风险不小，但还没到系统性危机",
      type: "信用专题",
      institution: "摩根士丹利",
      desk: "全球信用策略",
      theme: "信用交易",
      quote: "要把信用风险和系统性风险分开看，现在更像压力测试，不像全面失控。",
      summary:
        "摩根士丹利认为私募信贷的赎回压力、BDC 赎回和软件敞口值得警惕，但当前更像信用周期中的压力暴露，而不是会立刻引发系统性风险的失控事件。",
      takeaway:
        "私募信贷要更挑资产和敞口，但没必要直接按系统性危机去定价。",
      conviction: 78,
      surprise: 75,
      divergence: 79,
      sourceId: 610658,
      signals: [
        {
          asset: "私募信贷",
          direction: "neutral",
          score: 61,
          horizon: "1-3月",
          driver: "违约和赎回压力上升，但还不足以触发全面流动性失控",
          expression: "私募信贷按分化而非全面崩塌来处理",
          invalidation: "赎回门槛频繁触发并出现更广泛违约扩散",
        },
        {
          asset: "BDC股票",
          direction: "bearish",
          score: 70,
          horizon: "短中期",
          driver: "赎回和软件敞口担忧会先打压流动性更高的私募信贷代理资产",
          expression: "BDC 先按压力传导的交易载体来处理",
          invalidation: "私募信贷赎回压力明显缓和",
        },
        {
          asset: "杠杆贷款",
          direction: "bearish",
          score: 68,
          horizon: "1-3月",
          driver: "私募信贷压力外溢会抬高低质量信用的风险补偿要求",
          expression: "杠杆贷款先保持更高风险溢价假设",
          invalidation: "违约率和融资条件重新稳定",
        },
      ],
    },
  ],
};
